### PR TITLE
fix docker & ccache

### LINKED ISSUE #195: fix docker builds
- [ ] fix tests not running in docker
    + https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/483407710#L5255
    + [x] ensure future failures will not be silently ignored
- [x] ~~fix docker login~~
    + https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/483407710#L5234
    + ~~https://community.atlassian.com/t5/Bitbucket-questions/Piplenes-docker-login-can-not-perform-an-interactive-login-from/qaq-p/595736~~
    + https://discuss.bitrise.io/t/docker-login-failed-only-pr-trigger/2232
        * intentionally cannot build docker on PRs (security)

depends on #212 -> #213

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] fix docker builds: fix #195, partially revert #209
  - [x] ensure docker builds do not fail silently: fixes #194
  - [x] upgrade docker images to ubuntu 18.04 (from 16.04)
    - [x] fix boost
- [x] use ACE, ITK in docker builds
- [x] fix ccache in docker
- [x] use newer ccache syntax for normal travis builds

depends on #212 -> #213

### CODE REVIEW

**Comment by casperdcl** [comment]
ok now getting (https://api.travis-ci.org/v3/job/499919417/log.txt):
```
test 3
    Start 3: Gadgetron_TESTS
...
3: 1: [  FAILED  ] 2 tests, listed below:
3: 1: [  FAILED  ] hoNDArray_blas_Cplx/0.nrm2Test, where TypeParam = std::complex<float>
3: 1: [  FAILED  ] hoNDArray_blas_Cplx/2.nrm2Test, where TypeParam = Gadgetron::complext<float>
```

**Comment by KrisThielemans** [comment]
hmmm. strange as 18.04 is their reference system. 

I'll try to see in a VM if I can reproduce this. Only possibly reason that I see is the addition of the two `CBLAS` lines [when building Gadgetron](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/b3a05dabefd50b8870bf9c920f11b62dec46374c/SuperBuild/External_Gadgetron.cmake#L114)? sorry. not really what you want to have to fix.

**Comment by casperdcl** [comment]
Turns out `libatlas-base-dev` was required (https://github.com/CCPPETMR/SIRF-SuperBuild/issues/195#issuecomment-467510107) even though their [List of Dependencies](https://github.com/gadgetron/gadgetron/wiki/List-of-Dependencies) does not mention it.

In the end I just used

https://github.com/gadgetron/gadgetron/blob/b03e500e09d6b60f2ce94c859ee07fa95d6c0a4f/docker/base/ubuntu_1804/Dockerfile#L8-L10

File: docker/build_system-ubuntu.sh [hunk 1]
```diff
@@ -3,15 +3,11 @@ set -ev
 # SIRF external dependencies
 apt-get update -qq
 apt-get install -yq --no-install-recommends \
-  hdf5-tools           \
   hdfview              \
-  libarmadillo-dev     \
   libboost-all-dev     \
-  libfftw3-dev         \
   libgtest-dev         \
-  libhdf5-serial-dev   \
```
Comment (KrisThielemans) [inline docker/build_system-ubuntu.sh]: required for ISMRMRD, and without it, SIRF can do nothing with MR

File: docker/build_system-ubuntu.sh [hunk 2]
```diff
@@ -3,15 +3,11 @@ set -ev
 # SIRF external dependencies
 apt-get update -qq
 apt-get install -yq --no-install-recommends \
-  hdf5-tools           \
   hdfview              \
```
Comment (KrisThielemans) [inline docker/build_system-ubuntu.sh]: we don't need `hdfview`

File: docker/build_system-ubuntu.sh [hunk 3]
```diff
@@ -3,15 +3,11 @@ set -ev
...
-  libarmadillo-dev     \
   libboost-all-dev     \
-  libfftw3-dev         \
```
Comment (KrisThielemans) [inline docker/build_system-ubuntu.sh]: this file is for SIRF dependencies (or at least that's what the Dockerfile says). But SIRF currently still needs fftw.

File: .travis.yml [hunk 4]
```diff
@@ -219,19 +219,13 @@ before_install:
  - $PY_EXE --version
  - $PY_EXE -m pip --version
  - $PY_EXE -m pip freeze
- # ccache compiler override
```
Comment (KrisThielemans) [inline .travis.yml]: I don't think we can remove these. see below

File: .travis.yml [hunk 5]
```diff
@@ -219,19 +219,13 @@ before_install:
...
- - ln -s "$(which ccache)" g++-6
- - ln -s "$(which ccache)" g++-7
- - ln -s "$(which ccache)" gcc
- - ln -s "$(which ccache)" gcc-6
- - ln -s "$(which ccache)" gcc-7
  - export PATH="$PWD:$PATH"
  - popd
  # N.B.: don't put into build matrix to allow caching.
  - BUILD_FLAGS="$BUILD_FLAGS -DPYVER=$PYMVER"
+ - BUILD_FLAGS="$BUILD_FLAGS -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache"
```
Comment (KrisThielemans) [inline .travis.yml]: This will only work for CMake projects. Boost, FFTW etc however don't use CMake. We could/should pass `CMAKE_C_COMPILER_LAUNCHER` on in the relevant `External*.cmake`. However that is going to be quite tricky (certainly so for Boost who have a very different way to select compilers).

File: docker/build_system-ubuntu.sh (hunk 3 above)
Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: OK. RE: dependencies, which of the following are required by SIRF assuming BUILD_GADGETRON=OFF?

In particular, `*` means required by Gadgetron, but not necessarily SIRF. Useful to know for #91.

# old `build_system-ubuntu.sh`
- [ ] *hdf5-tools
- [ ] hdfview
- [ ] *libarmadillo-dev
- [ ] *libboost-all-dev
- [ ] *libfftw3-dev
- [ ] libgtest-dev
- [ ] *libhdf5-serial-dev
- [ ] *libplplot-dev
- [ ] *libxml2-dev
- [ ] *libxslt-dev
# old `build_gadgetron-ubuntu.sh`
- [ ] *h5utils
- [ ] *libace-dev
- [ ] *liblapack-dev

File: .travis.yml (hunk 5 above)
Comment (casperdcl) [reply .travis.yml]: ah pity

File: .travis.yml (hunk 4 above)
Comment (casperdcl) [reply .travis.yml]: k will revert

File: docker/build_system-ubuntu.sh (hunk 2 above)
Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: [comment below](https://github.com/CCPPETMR/SIRF-SuperBuild/pull/214/files/6563e5ee60963b71370a41210c535ef50fb8fd45#r261585587)

File: docker/build_system-ubuntu.sh (hunk 1 above)
Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: [comment above](https://github.com/CCPPETMR/SIRF-SuperBuild/pull/214/files/6563e5ee60963b71370a41210c535ef50fb8fd45#r261585587)

File: docker/user_sirf-ubuntu.sh [hunk 6]
```diff
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
-set -ev
 [ -f .bashrc ] && . .bashrc
+set -ev
 # SIRF
-git clone https://github.com/CCPPETMR/SIRF-SuperBuild --recursive -b master /opt/SIRF-SuperBuild
+git clone https://github.com/CCPPETMR/SIRF-SuperBuild --recursive -b docker /opt/SIRF-SuperBuild
```
Comment (casperdcl) [inline docker/user_sirf-ubuntu.sh]: to revert before/during merge

File: docker/build_system-ubuntu.sh (hunk 3 above)
Comment (KrisThielemans) [reply docker/build_system-ubuntu.sh]: i'm fairly sure there's only 3. There's also swig. Indeed, the superbuild builds all SIRF dependencies...

(Gadgetron doesn't need `plplot`, it enables extra functionality, I think only for plotting but I don't know).

File: docker/build_system-ubuntu.sh (hunk 2 above)
Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: ah but should it be included anyway just in case people want it? Perhaps under a separate list of "completely optional"?

Comment (KrisThielemans) [reply docker/build_system-ubuntu.sh]: could do, `hdf5view` is in the same category

Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: continued in #216

File: docker/build_system-ubuntu.sh (hunk 3 above)
Comment (casperdcl) [reply docker/build_system-ubuntu.sh]: continued in #216
